### ISSUE TITLE
Global Sitemap generated for all exhibits has bad URLs

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/exhibits_request#33]
The base robots.txt athttps://exhibits.stanford.edu/robots.txt  references a sitemap.xml that points to each exhibit specific sitemap for exhibits that are published.  The urls are wrong: "https://exhibits.stanford.edu/https://exhibits.stanford.edu/mss/sitemap.xml.gz"

**Comment by ndushay** [comment]
@cbeer @peetucket  did this get fixed with sul-dlss/sul_exhibits_template#105 ?

**Comment by peetucket** [comment]
@ndushay nope, this one fixes it: #34
